//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotalSystem.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOut
    {
        public int checkout_id { get; set; }
        public int reserva_id { get; set; }
        public int empleado_id { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public decimal total_factura { get; set; }
        public string metodo_pago_final { get; set; }
        public string observaciones { get; set; }

        [JsonIgnore]
        public virtual Empleado Empleado { get; set; }
        [JsonIgnore]
        public virtual Reserva Reserva { get; set; }
    }
}
