//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotalSystem.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Consumo_Servicio
    {
        public int consumo_servicio_id { get; set; }
        public int reserva_id { get; set; }
        public int servicio_id { get; set; }
        public Nullable<System.DateTime> fecha_hora_consumo { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario_cobrado { get; set; }
        public Nullable<int> empleado_registro_id { get; set; }

        [JsonIgnore]

        public virtual Empleado Empleado { get; set; }

        [JsonIgnore]
        public virtual Reserva Reserva { get; set; }

        [JsonIgnore]
        public virtual Servicio Servicio { get; set; }
    }
}
