//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Pedido_Suministro
    {
        public int detalle_pedido_id { get; set; }
        public int pedido_id { get; set; }
        public int item_suministro_id { get; set; }
        public int cantidad_pedida { get; set; }
        public Nullable<int> cantidad_recibida { get; set; }
        public decimal precio_unitario_pedido { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual Item_Suministro Item_Suministro { get; set; }
        public virtual Pedido_Suministro Pedido_Suministro { get; set; }
    }
}
