//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotalSystem.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Paquete_Servicio
    {
        public int paquete_servicio_id { get; set; }
        public int paquete_id { get; set; }
        public int servicio_id { get; set; }
        public int cantidad_incluida { get; set; }

        [JsonIgnore]
        public virtual Paquete Paquete { get; set; }

        [JsonIgnore]
        public virtual Servicio Servicio { get; set; }
    }
}
