//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Empleadoes = new HashSet<Empleado>();
            this.Habitacions = new HashSet<Habitacion>();
            this.Inventario_Hotel = new HashSet<Inventario_Hotel>();
            this.Pedido_Suministro = new HashSet<Pedido_Suministro>();
            this.Reservas = new HashSet<Reserva>();
            this.Restaurantes = new HashSet<Restaurante>();
            this.Servicios = new HashSet<Servicio>();
        }
    
        public int hotel_id { get; set; }
        public Nullable<int> cadena_id { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public int ciudad_id { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<int> estrellas { get; set; }
        public System.DateTime fecha_apertura { get; set; }
        public string estado_operativo { get; set; }
        public string politica_cancelacion { get; set; }
        public Nullable<int> gerente_id { get; set; }
    
        public virtual Cadena_Hotelera Cadena_Hotelera { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habitacion> Habitacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario_Hotel> Inventario_Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Suministro> Pedido_Suministro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reservas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurante> Restaurantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio> Servicios { get; set; }
    }
}
