//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario_Hotel
    {
        public int inventario_id { get; set; }
        public int hotel_id { get; set; }
        public int item_suministro_id { get; set; }
        public Nullable<int> stock_actual { get; set; }
        public Nullable<int> stock_minimo { get; set; }
        public Nullable<System.DateTime> fecha_ultima_actualizacion { get; set; }
        public string ubicacion_almacen { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Item_Suministro Item_Suministro { get; set; }
    }
}
