//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Suministro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_Suministro()
        {
            this.Detalle_Pedido_Suministro = new HashSet<Detalle_Pedido_Suministro>();
            this.Inventario_Hotel = new HashSet<Inventario_Hotel>();
        }
    
        public int item_suministro_id { get; set; }
        public int proveedor_id { get; set; }
        public string nombre_item { get; set; }
        public string descripcion { get; set; }
        public string unidad_medida { get; set; }
        public decimal precio_unitario_proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Pedido_Suministro> Detalle_Pedido_Suministro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario_Hotel> Inventario_Hotel { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
