//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotalSystem.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_Suministro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido_Suministro()
        {
            this.Detalle_Pedido_Suministro = new HashSet<Detalle_Pedido_Suministro>();
        }
    
        public int pedido_id { get; set; }
        public int hotel_id { get; set; }
        public int proveedor_id { get; set; }
        public int empleado_id { get; set; }
        public Nullable<System.DateTime> fecha_pedido { get; set; }
        public Nullable<System.DateTime> fecha_entrega_esperada { get; set; }
        public Nullable<System.DateTime> fecha_entrega_real { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> total { get; set; }
        public string notas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [JsonIgnore]
        public virtual ICollection<Detalle_Pedido_Suministro> Detalle_Pedido_Suministro { get; set; }

        [JsonIgnore]
        public virtual Empleado Empleado { get; set; }

        [JsonIgnore]
        public virtual Hotel Hotel { get; set; }

        [JsonIgnore]
        public virtual Proveedor Proveedor { get; set; }
    }
}
