// <auto-generated />
namespace HotelAuroraDreams.Api_Framework.Migrations.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InitialIdentitySchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialIdentitySchema));
        
        string IMigrationMetadata.Id
        {
            get { return "202506020106091_InitialIdentitySchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
