//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAuroraDreams.Api_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Paquete_Transporte
    {
        public int paquete_transporte_id { get; set; }
        public int paquete_id { get; set; }
        public int transporte_id { get; set; }
        public string tipo_trayecto { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
    
        public virtual Paquete Paquete { get; set; }
        public virtual Transporte Transporte { get; set; }
    }
}
