//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAuroraDreams.Api_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaEvento()
        {
            this.DetalleFacturaEventoes = new HashSet<DetalleFacturaEvento>();
        }
    
        public int FacturaEventoID { get; set; }
        public int ReservaEventoID { get; set; }
        public int ClienteID { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public decimal SubtotalSalon { get; set; }
        public decimal SubtotalServiciosAdicionales { get; set; }
        public decimal Impuestos { get; set; }
        public decimal TotalFactura { get; set; }
        public string MetodoPago { get; set; }
        public string Estado { get; set; }
        public Nullable<int> EmpleadoEmisorID { get; set; }
        public string Notas { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaEvento> DetalleFacturaEventoes { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual ReservaEvento ReservaEvento { get; set; }
    }
}
