//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAuroraDreams.Api_Framework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManagementSystemEntities : DbContext
    {
        public HotelManagementSystemEntities()
            : base("name=HotelManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cadena_Hotelera> Cadena_Hotelera { get; set; }
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<CheckIn> CheckIns { get; set; }
        public virtual DbSet<CheckOut> CheckOuts { get; set; }
        public virtual DbSet<Ciudad> Ciudads { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Consumo_Servicio> Consumo_Servicio { get; set; }
        public virtual DbSet<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual DbSet<Detalle_Paquete_Servicio> Detalle_Paquete_Servicio { get; set; }
        public virtual DbSet<Detalle_Paquete_Transporte> Detalle_Paquete_Transporte { get; set; }
        public virtual DbSet<Detalle_Pedido_Suministro> Detalle_Pedido_Suministro { get; set; }
        public virtual DbSet<DetalleFacturaEvento> DetalleFacturaEventoes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<FacturaEvento> FacturaEventoes { get; set; }
        public virtual DbSet<Habitacion> Habitacions { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Inventario_Hotel> Inventario_Hotel { get; set; }
        public virtual DbSet<Item_Suministro> Item_Suministro { get; set; }
        public virtual DbSet<Paquete> Paquetes { get; set; }
        public virtual DbSet<Pedido_Suministro> Pedido_Suministro { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Reserva> Reservas { get; set; }
        public virtual DbSet<Reserva_Habitacion> Reserva_Habitacion { get; set; }
        public virtual DbSet<Reserva_Paquete> Reserva_Paquete { get; set; }
        public virtual DbSet<Reserva_Restaurante> Reserva_Restaurante { get; set; }
        public virtual DbSet<ReservaEvento> ReservaEventoes { get; set; }
        public virtual DbSet<ReservaEvento_Servicio> ReservaEvento_Servicio { get; set; }
        public virtual DbSet<Restaurante> Restaurantes { get; set; }
        public virtual DbSet<SalonEvento> SalonEventoes { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<ServicioAdicionalEvento> ServicioAdicionalEventoes { get; set; }
        public virtual DbSet<Tipo_Habitacion> Tipo_Habitacion { get; set; }
        public virtual DbSet<Tipo_Servicio> Tipo_Servicio { get; set; }
        public virtual DbSet<Tipo_Transporte> Tipo_Transporte { get; set; }
        public virtual DbSet<TipoEvento> TipoEventoes { get; set; }
        public virtual DbSet<Transporte> Transportes { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
