//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAuroraDreams.Api_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva_Restaurante
    {
        public int reserva_restaurante_id { get; set; }
        public int cliente_id { get; set; }
        public int restaurante_id { get; set; }
        public System.DateTime fecha_reserva { get; set; }
        public System.TimeSpan hora_reserva { get; set; }
        public int numero_comensales { get; set; }
        public string estado { get; set; }
        public string notas { get; set; }
        public Nullable<int> empleado_registro_id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Restaurante Restaurante { get; set; }
    }
}
