//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAuroraDreams.Api_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservaEvento()
        {
            this.FacturaEventoes = new HashSet<FacturaEvento>();
            this.ReservaEvento_Servicio = new HashSet<ReservaEvento_Servicio>();
        }
    
        public int ReservaEventoID { get; set; }
        public int ClienteID { get; set; }
        public int SalonEventoID { get; set; }
        public Nullable<int> TipoEventoID { get; set; }
        public string NombreEvento { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public System.DateTime FechaEvento { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFin { get; set; }
        public int NumeroAsistentesEstimado { get; set; }
        public Nullable<int> NumeroAsistentesConfirmado { get; set; }
        public Nullable<int> EmpleadoResponsableID { get; set; }
        public string Estado { get; set; }
        public string Notas { get; set; }
        public Nullable<decimal> MontoEstimadoSalon { get; set; }
        public Nullable<decimal> MontoEstimadoServicios { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaEvento> FacturaEventoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaEvento_Servicio> ReservaEvento_Servicio { get; set; }
        public virtual SalonEvento SalonEvento { get; set; }
        public virtual TipoEvento TipoEvento { get; set; }
    }
}
