//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAuroraDreams.Api_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva_Habitacion
    {
        public int reserva_habitacion_id { get; set; }
        public int reserva_id { get; set; }
        public int habitacion_id { get; set; }
        public decimal precio_noche_cobrado { get; set; }
        public string estado_asignacion { get; set; }
    
        public virtual Habitacion Habitacion { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
