//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAuroraDreams.Api_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva_Paquete
    {
        public int reserva_paquete_id { get; set; }
        public int reserva_id { get; set; }
        public int paquete_id { get; set; }
        public Nullable<System.DateTime> fecha_reserva_paquete { get; set; }
        public decimal precio_cobrado { get; set; }
        public string estado { get; set; }
    
        public virtual Paquete Paquete { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
