//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAuroraDreams.Api_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaEvento_Servicio
    {
        public int ReservaEventoID { get; set; }
        public int ServicioAdicionalID { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioCobradoPorUnidad { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public string Notas { get; set; }
    
        public virtual ReservaEvento ReservaEvento { get; set; }
        public virtual ServicioAdicionalEvento ServicioAdicionalEvento { get; set; }
    }
}
