//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAuroraDreams.Api_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurante()
        {
            this.Reserva_Restaurante = new HashSet<Reserva_Restaurante>();
        }
    
        public int restaurante_id { get; set; }
        public int hotel_id { get; set; }
        public string nombre { get; set; }
        public string tipo_cocina { get; set; }
        public Nullable<System.TimeSpan> horario_apertura { get; set; }
        public Nullable<System.TimeSpan> horario_cierre { get; set; }
        public Nullable<int> capacidad_mesas { get; set; }
        public string descripcion { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva_Restaurante> Reserva_Restaurante { get; set; }
    }
}
