//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAuroraDreams.Api_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.Consumo_Servicio = new HashSet<Consumo_Servicio>();
            this.Detalle_Paquete_Servicio = new HashSet<Detalle_Paquete_Servicio>();
        }
    
        public int servicio_id { get; set; }
        public int hotel_id { get; set; }
        public int tipo_servicio_id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precio_base { get; set; }
        public string horario { get; set; }
        public Nullable<int> capacidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumo_Servicio> Consumo_Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Paquete_Servicio> Detalle_Paquete_Servicio { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Tipo_Servicio Tipo_Servicio { get; set; }
    }
}
