//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAuroraDreams.Api_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transporte()
        {
            this.Detalle_Paquete_Transporte = new HashSet<Detalle_Paquete_Transporte>();
        }
    
        public int transporte_id { get; set; }
        public int tipo_transporte_id { get; set; }
        public string descripcion { get; set; }
        public string compania { get; set; }
        public int capacidad { get; set; }
        public decimal precio_base { get; set; }
        public string notas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Paquete_Transporte> Detalle_Paquete_Transporte { get; set; }
        public virtual Tipo_Transporte Tipo_Transporte { get; set; }
    }
}
